const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("sshDock", {
  platform: process.platform,
  listConnections: () => ipcRenderer.invoke("connections:list"),
  saveConnection: (connection) => ipcRenderer.invoke("connections:save", connection),
  deleteConnection: (id) => ipcRenderer.invoke("connections:delete", id),
  chooseKeyPath: () => ipcRenderer.invoke("dialog:keyPath"),
  connect: (payload) => ipcRenderer.invoke("ssh:connect", payload),
  sendInput: (payload) => ipcRenderer.send("ssh:input", payload),
  resize: (payload) => ipcRenderer.send("ssh:resize", payload),
  disconnect: (sessionId) => ipcRenderer.invoke("ssh:disconnect", sessionId),
  uploadFile: (payload) => ipcRenderer.invoke("ssh:upload", payload),
  listRemoteDir: (payload) => ipcRenderer.invoke("ssh:listdir", payload),
  remoteHome: (sessionId) => ipcRenderer.invoke("ssh:home", { sessionId }),
  showFileMenu: (payload) => ipcRenderer.invoke("ui:file-menu", payload),
  chooseDownloadFolder: (payload) => ipcRenderer.invoke("dialog:choose-folder", payload),
  downloadRemoteTo: (payload) => ipcRenderer.invoke("ssh:download-to", payload),
  revealInFolder: (localPath) => ipcRenderer.send("shell:reveal-item", localPath),
  makeRemoteDir: (payload) => ipcRenderer.invoke("ssh:mkdir", payload),
  removeRemote: (payload) => ipcRenderer.invoke("ssh:rm", payload),
  createLocalTerminal: (payload) => ipcRenderer.invoke("localterm:create", payload),
  localTerminalCwd: (sessionId) => ipcRenderer.invoke("localterm:cwd", sessionId),
  loadTerminalGroups: () => ipcRenderer.invoke("termgroups:load"),
  saveTerminalGroups: (groups) => ipcRenderer.invoke("termgroups:save", groups),
  openTerminalWindow: (payload) => ipcRenderer.invoke("terminal:open-window", payload),
  terminalSnapshot: (sessionId) => ipcRenderer.invoke("terminal:snapshot", sessionId),
  hasActiveTask: (sessionId) => ipcRenderer.invoke("terminal:has-active-task", sessionId),
  onData: (callback) => ipcRenderer.on("ssh:data", (_event, payload) => callback(payload)),
  onStats: (callback) => ipcRenderer.on("ssh:stats", (_event, payload) => callback(payload)),
  onUploadProgress: (callback) => ipcRenderer.on("ssh:upload-progress", (_event, payload) => callback(payload)),
  onDownloadProgress: (callback) => ipcRenderer.on("ssh:download-progress", (_event, payload) => callback(payload)),
  onClosed: (callback) => ipcRenderer.on("ssh:closed", (_event, payload) => callback(payload)),
  onError: (callback) => ipcRenderer.on("ssh:error", (_event, payload) => callback(payload)),
  onTerminalWindowClosed: (callback) => ipcRenderer.on("terminal:window-closed", (_event, payload) => callback(payload))
});
